
start: scope*

scope: "scope" scope_name "{" (pre | post | op | global | header | parse | with)* "}"

scope_name: NAME (":" NAME)

parse: "parse" NAME block

header: "header" block

global: "global" block

pre: "pre" block

post: "post" block

with: "with" "{" with_decl* "}"

with_decl: NAME NAME ";"

op: "op" NAME (arg ("," arg)*)? block

arg: "(" NAME NAME ")"

block: "{" LINE? (block LINE)* "}"

LINE: /[^{}]+/

NAME: /[a-z_A-Z][a-z_A-Z0-9]*/

%ignore /[ \t\r\n]+/
